services:
    backend:
        container_name: api
        build:
            dockerfile: Dockerfile
            context: .
        env_file: .env.docker
        ports:
            - '8080:8080'
        volumes:
            - .:/home/app:cached
            - ./package.json:/home/app/package.json:cached
        depends_on:
            database:
                condition: service_healthy
        networks:
            - gen-services

    database:
        image: postgres:14.4-alpine
        container_name: todo-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: todo-db
        ports:
            - 5432:5432
        networks:
            - gen-services
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5

networks:
    gen-services:
        driver: bridge
